# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='post',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='post',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
