# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170725_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='tag',
            new_name='name',
        ),
    ]
