# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170730_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='id',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
